---
layout: cv
title: Kristal Eng's CV
---
# Kristal Eng
current Brigham Young University - Idaho student

<div id="webaddress">
<a href="https://laughing-adventure-wgromre.pages.github.io/">Github</a>
| <a href="https://www.linkedin.com/in/kristal-eng-450401204/
">Linkedin</a>
</div>

## Contact Information

Mobile: +1 (208) 973-5574

Email: kristaleng.by@gmail.com

## Searching for

Internships, full-time positions


### Specialized in

Microsoft Excel, SQL


### Languages

- English
- Mandarin Chinese


## Education

`Sep 2023 - current`

__Brigham Young University - Idaho__

- Bachelor of Science in Business Analytics
 - Minor in Economics



`Apr 2017 - May 2020`

__Nanyang Polytechnic, Singapore__

- Diploma in Biologics and Process Technology (Associates)


## Work Experience

- __Teacher's Assistant__, 2023 - current

Brigham Young University - Idaho | USA


- __Part Time Service Crew__, Mar 2023 - Sep 2023

iSteaks Restaurant | Singapore


- __Paralegal__, Aug 2022 - Feb 2023

Nanyang Law LLC | Singapore


- __Financial Consultant__, Aug 2021 - Jul 2022

Prudential Assurance Company Singapore | Singapore


## Volunteer Work

- _BYUI HJG Mentoring Program_
- _Chinese Conversation Lab_


<!-- ### Footer

Last updated: Dec 2024 -->